# Generated by Django 5.2 on 2025-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='member_since',
            field=models.DateField(),
        ),
    ]
