# Generated by Django 5.2 on 2025-04-04 14:41

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_customuser_address_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', upload_to=Users.models.user_phpoto_path),
        ),
    ]
